# Generated by Django 4.0.5 on 2022-06-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок статьи')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации статьи')),
                ('public', models.BooleanField(default=False, verbose_name='Публичная статья')),
            ],
        ),
    ]
